/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todolist.app;

public class App {

  public static void main(String[] args) {
    new App().helloWorld();
  }

  public void helloWorld() {
    System.out.println("Hello, World!");
  }
}
